-- 🧑‍💼 Revenue generated by each customer
SELECT 
  c.customer_key,
  c.first_name,
  c.last_name,
  SUM(f.sales) AS total_sales
FROM g_fact_sales f
LEFT JOIN g_dim_customers c ON c.customer_key = f.customer_key
GROUP BY c.customer_key, c.first_name, c.last_name
ORDER BY total_sales DESC;

-- 🌍 Distribution of quantity sold across countries
SELECT c.country, SUM(f.quantity) AS quantity_sold
FROM g_fact_sales f
LEFT JOIN g_dim_customers c ON c.customer_key = f.customer_key
GROUP BY c.country
ORDER BY quantity_sold DESC;
