-- 🌍 Total customers by country
SELECT COUNT(DISTINCT customer_id) AS total_customers, country
FROM g_dim_customers
GROUP BY country
ORDER BY total_customers DESC;

-- 🚻 Total customers by gender
SELECT COUNT(DISTINCT customer_id) AS total_customers, gender
FROM g_dim_customers
GROUP BY gender
ORDER BY gender;

-- 📂 Total products by category
SELECT COUNT(product_key) AS total_products, category
FROM g_dim_products
GROUP BY category
ORDER BY category;

-- 💸 Average cost per category
SELECT AVG(cost) AS avg_cost, category
FROM g_dim_products
GROUP BY category
ORDER BY category;

-- 💰 Revenue generated by each category
SELECT p.category, SUM(f.sales) AS total_revenue
FROM g_fact_sales f
LEFT JOIN g_dim_products p ON p.product_key = f.product_key
GROUP BY p.category
ORDER BY total_revenue DESC;
